app/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.ArticlesView.as_view(), name='index'),
    path('<int:pk>/', views.ArticlesDetailView.as_view(), name='detail'),
    path('author/<int:pk>/', views.AuthorArticlesView.as_view(), name='author'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('articles.urls', namespace='articles')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.UserRegistrationView.as_view(), name='register'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name="logout"),
    path(
        'article/<int:article_id>/', views.FavouriteArticleView.as_view(),
        name='favourite_article'),
    path(
        'author/<int:author_id>/', views.FavouriteAuthorView.as_view(),
        name='favourite_author'),
]

app/articles/models.py
import logging
from typing import Any, List

from bs4 import BeautifulSoup
from dateutil import parser
from django.conf import settings
from django.db import models
from django.db.utils import IntegrityError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


class AbstractBaseModel(models.Model):
    id = models.IntegerField(primary_key=True, editable=False)
    timestamp = models.DateTimeField(default=timezone.now, blank=True)

    class Meta:
        abstract = True
        ordering = ['-timestamp']


class Category(AbstractBaseModel):
    """
    Article Category
    """
    name = models.CharField(
        max_length=255, null=False, blank=False, unique=True)
    code = models.CharField(
        max_length=255, null=False, blank=False, unique=True,
        help_text='A unique code that identifies the category'
    )
    last_sync_date = models.DateField(null=True, blank=True, default=None)

    def __str__(self) -> str:
        return self.name

    def get_sync_interval_days(self) -> int:
        if not self.last_sync_date:
            return settings.INITIAL_SYNC_FETCH_INTERVAL_DAYS

        delta = timezone.now().date() - self.last_sync_date

        if delta.days > settings.INITIAL_SYNC_FETCH_INTERVAL_DAYS:
            return settings.INITIAL_SYNC_FETCH_INTERVAL_DAYS
        return delta.days

    def sync_articles(self, articles_data_fetch_resonse):
        from articles.models import Article
        logging.info(
            f'Syncing articles for category : {self.name} '
            f'with params: {articles_data_fetch_resonse}'
        )
        parsed_response = BeautifulSoup(
            articles_data_fetch_resonse.respone.text,
            features='lxml'
        )
        records = parsed_response.findAll('record')

        for record in records:
            article_external_id = record.find('arxiv').find('id').text

            article = None

            try:
                category = None
                try:
                    category_code = record.find('header').find('setspec').text
                    category = Category.objects.get(code=category_code)
                except Category.DoesNotExist:
                    # Skip over categories we don't recognise
                    continue

                metadata = record.find('arxiv')
                created_on = metadata.find('created').text
                updated_on_element = metadata.find('updated')
                updated_on = (
                    updated_on_element.text if updated_on_element else created_on
                )
                authors = metadata.find('authors').findAll('author')
                title = metadata.find('title').text
                sub_categories = metadata.find('categories').text
                summary = metadata.find('abstract').text
                article = Article.objects.create(
                    created_on=parser.parse(created_on, dayfirst=False),
                    updated_on=parser.parse(updated_on, dayfirst=False),
                    title=title,
                    external_id=article_external_id,
                    summary=summary,
                    category=category
                )
                article.save()
            except IntegrityError:
                article = Article.objects.get(external_id=article_external_id)

            ArticleAuthor.sync_article_authors(
                article=article,
                author_elements=authors
            )

            ArticleSubCategory.sync_article_sub_categories(
                article=article,
                sub_categories=sub_categories
            )

        # Update last sync date
        self.last_sync_date = articles_data_fetch_resonse.end_date
        self.save()

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class SubCategory(AbstractBaseModel):
    """
    Article sub category
    """
    category = models.ForeignKey(
        Category, null=False, blank=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=False, blank=False)
    code = models.CharField(
        max_length=255, null=False, blank=False, unique=True,
        help_text="A unique code that identifies the sub category"
    )

    def __str__(self) -> str:
        return self.name

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('subcategory')
        verbose_name_plural = _('subcategories')
        unique_together = ('name', 'code')


class Author(AbstractBaseModel):
    last_name = models.CharField(max_length=255, null=False, blank=False)
    first_name = models.CharField(max_length=255, null=False, blank=False)

    def __str__(self) -> str:
        return f'{self.last_name} {self.first_name}'

    @property
    def name(self) -> str:
        return f'{self.last_name} {self.first_name}'

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('author')
        verbose_name_plural = _('authors')
        unique_together = ('last_name', 'first_name')


class Article(AbstractBaseModel):
    created_on = models.DateField(null=True, blank=True, default=None)
    updated_on = models.DateField(null=True, blank=True, default=None)
    title = models.CharField(max_length=255, null=False, blank=False)
    external_id = models.CharField(
        max_length=255, null=False, blank=False, unique=True,
        help_text="Article identifier in the external source")
    summary = models.TextField(null=False, blank=False)
    category = models.ForeignKey(
        Category, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('article')
        verbose_name_plural = _('articles')
        ordering = ['-updated_on']
        indexes = [
            models.Index(fields=('updated_on',)),
            models.Index(fields=('created_on',)),
        ]


class ArticleAuthor(AbstractBaseModel):
    author = models.ForeignKey(
        Author, null=False, blank=False, on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'Author: {self.author.name} | Article: {self.article.title}'

    @classmethod
    def sync_article_authors(cls, article: Article, author_elements: List[Any]) -> None:
        for author_element in author_elements:
            last_name_element = author_element.find('keyname')
            first_name_element = author_element.find('forenames')

            if last_name_element is None:
                continue

            last_name = last_name_element.text
            first_name = first_name_element.text if first_name_element else last_name

            author = None

            try:
                author = Author.objects.create(
                    first_name=first_name,
                    last_name=last_name
                )
                author.save()
            except IntegrityError:
                author = Author.objects.get(
                    first_name=first_name,
                    last_name=last_name
                )

            if author:
                try:
                    author.articleauthor_set.create(article=article)
                except IntegrityError:
                    # the article author already exists
                    pass

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('article_author')
        verbose_name_plural = _('article_authors')
        unique_together = ('article', 'author')


class ArticleSubCategory(AbstractBaseModel):
    article = models.ForeignKey(
        Article, null=False, blank=False, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(
        SubCategory, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return (
            f'SubCategory: {self.sub_category.id} | '
            f'Article: {self.article.id}'
        )

    @classmethod
    def sync_article_sub_categories(
        cls,
        article: Article,
        sub_categories: str
    ) -> None:
        sub_categories_codes = sub_categories.split(' ')

        for sub_category_code in sub_categories_codes:
            try:
                sub_category = SubCategory.objects.get(code=sub_category_code)
                cls.objects.create(
                    article=article,
                    sub_category=sub_category
                )
            except SubCategory.DoesNotExist:
                # Ignore sub categories we cannot recognise
                pass
            except IntegrityError:
                # article subcategory already exists
                pass

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('article_subcategory')
        verbose_name_plural = _('article_subcategories')
        unique_together = ('article', 'sub_category')

app/articles/views.py
from typing import Any, Dict
from users.models import UserFavourite

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views.generic import DetailView, ListView

from articles.models import Article, ArticleAuthor, Author


class ArticlesView(ListView):
    template_name = 'articles/list.html'
    context_object_name = 'articles'
    paginate_by = 25

    def get_queryset(self) -> QuerySet:
        return Article.objects.all().select_related('category').order_by('-created_on')


class ArticlesDetailView(DetailView):
    model = Article
    template_name = 'articles/detail.html'
    has_favourite = False

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.has_favourite = UserFavourite.has_favourite(
            self.request.user, self.get_object())
        return super().dispatch(request, *args, **kwargs)


class AuthorArticlesView(ListView):
    template_name = 'author/list.html'
    context_object_name = 'author_articles'
    author = None
    paginate_by = 25

    has_favourite = False

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.has_favourite = UserFavourite.has_favourite(
            self.request.user, self.get_author())
        return super().dispatch(request, *args, **kwargs)

    def get_author(self):
        if self.author:
            return self.author
        self.author = Author.objects.get(pk=self.kwargs['pk'])
        return self.author

    def get_queryset(self) -> QuerySet:
        author = self.get_author()
        return ArticleAuthor.objects.filter(
            author=author
        ).select_related('article').order_by('-article__created_on')[:20]

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['author'] = self.get_author()
        return context_data

app/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block pre_content %}
    <h2 class="pb-2 border-bottom">
            {{ article.title }}
    </h2>

{% endblock pre_content %}
jj
{% block content %}

    {% if request.user and request.user.is_authenticated %}
        <span class="float-end">
            {% if not view.has_favourite %}
                    <form method="post" action="{% url 'users:favourite_article' article_id=article.id %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Favourite"/>
                    </form>
                    <br />&nbsp;
            {% else %}
                    <b > This is your favourite</b>
            {% endif %}
        </span>
    {% endif %}
    <table class="table table-bordered">
        <tbody>
                <tr>
                    <td>Id</td>
                    <td>{{ article.id }}</td>
                </tr>
                <tr>
                    <td>Title</td>
                    <td>{{ article.title }}</td>
                </tr>
                <tr>
                    <td>Created On</td>
                    <td>{{ article.created_on }}</td>
                </tr>
                <tr>
                    <td>Summary</td>
                    <td>{{ article.summary }}</td>
                </tr>

                <tr>
                    <td>Category</td>

                    <td>{{ article.category.name }}</td>
                </tr>
                <tr>
                    <td>Sub Categories</td>

                    <td> 
                        <ul>
                            {% for item in article.articlesubcategory_set.all %}
                                <li> {{ item.sub_category.name }} </li>
                            {% endfor %}

                        </ul>
                    </td>
                </tr>
                
        </tbody>
    </table>
    <h2 class="pb-2 border-bottom">
        Authors
    </h2>

    <table class="table table-striped table-hover">

        <thead>
            <tr>
                <th>#Id</th>
                <th>Name</th>
                <th>Total Articles</th>
            </tr>
        </thead>

        <tbody>
            {% for item in article.articleauthor_set.all %}
                <tr>
                    <td scope='row'>{{ item.author.id }}</td>
                    <td> 
                        <a href="{% url 'articles:author' item.author.id %}" > {{ item.author.name }}</a>
                    </td>
                    <td>{{ item.author.articleauthor_set.count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

app/articles/templates/articles/list.html
{% extends "base.html" %}

{% block pre_content %}
    <h2 class="pb-2 border-bottom">
        Published Articles
    </h2>
{% endblock pre_content %}

{% block content %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th># Id</th>
                <th>Title</th>
                <th>Category</th>
                <th>Created On</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                <tr>
                    <td scope="row">{{ article.id }}</td>
                    <td> <a href="{% url 'articles:detail' article.id %}" >{{ article.title }}</a> </td>
                    <td>{{ article.category.name }}</td>
                    <td>{{ article.created_on }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        {% include 'pagination.html' with page_obj=page_obj %}
    </div>
{% endblock content %}