app/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.ArticlesView.as_view(), name='index'),
    path('<int:pk>/', views.ArticlesDetailView.as_view(), name='detail'),
    path('author/<int:pk>/', views.AuthorArticlesView.as_view(), name='author'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('articles.urls', namespace='articles')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.UserRegistrationView.as_view(), name='register'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name="logout"),
    path(
        'article/<int:article_id>/', views.FavouriteArticleView.as_view(),
        name='favourite_article'),
    path(
        'author/<int:author_id>/', views.FavouriteAuthorView.as_view(),
        name='favourite_author'),
]

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
            <title>Research Publications</title>
            <meta charset="utf-8">
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta http-equiv="Content-Language" content="en">
            <meta name="viewport"
                content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no">
            <meta name="description" content="post projects, hire experts">
            <meta name="author" content="Liyosi Collins">

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    </head>
    <body>
        {% block header %}
            {% include 'header.html' %}
        {% endblock header  %}
        <div class="container">
            {% block container %}

                {% block pre_content %} {% endblock pre_content %}

                <div class="card">
                    <div class="card-body">
                        {% block content %} {% endblock content %}
                    </div>
                </div>

            {% endblock container %}

        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <body/>
</html>

app/templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'articles:index' %}" class="nav-link px-3 text-secondary">Home</a></li>
            </ul>

            <div class="text-end">
                {% if request.user and request.user.is_authenticated %}
                    <span> Welcome, {{ user.first_name }} {{ user.last_name}}</span>
                    <a href="{% url 'users:logout' %}" type="button" class="btn btn-warning">Logout </a>

                {% else %}
                    <a href="{% url 'users:login' %}"  type="button" class="btn btn-outline-light me-2">Login</a>
                    <a href="{% url 'users:register' %}" type="button" class="btn btn-warning">Sign-up</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

app/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>